name: Lint and Test

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"
      - name: Install linters
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install mvdan.cc/unparam@latest
      - name: go vet
        run: go vet ${{ inputs.path }}
      - name: staticcheck
        run: staticcheck ${{ inputs.path }}
      - name: unparam
        run: unparam ${{ inputs.path }}

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"
      - name: Run Tests
        run: go test -v ./...
